# vim: set filetype=yaml.docker-compose :
services:
  www:
    build:
      context: './www'
      dockerfile: 'dev.Dockerfile'
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
    ports:
      - '3000:3000'
    volumes:
      - './www:/www'
